### PAGE D'ACCUEIL

title: Site

#-----------------------------------------------------------------------------------

# 1. PROJETS
# 2. INFORMATIONS

#-----------------------------------------------------------------------------------

tabs:

#-- 1. PROJETS

  projets:
    label: Projets
    icon: image
    sections:
      projetsListed:
        type: pagetable
        headline: Projets
        template: projet
        status: all
        image:
          cover: true
        columns:
          title:
            label: Titre
            text: '{{ page.title }}'
            width: 1/4
          category:
            label: Catégorie(s)
            text: '{{ page.categorie.toCategory }}'
            width: 1/4
          legende:
            label: Légende
            text: '{{ page.legendeAuto.toCaption("home") }}'
            width: 1/2

      projetsDatas:
        type: fields
        fields:
          line-a:
            type: line

          bigSections:
            type: tags
            label: Sections
            layout: list
            width: 1/3
          clients:
            type: tags
            label: Clients
            layout: list
            width: 1/3
          collections: 
            type: tags
            label: Collections
            layout: list
            width: 1/3

#-- 2. INFORMATIONS

  informations:
    label: Informations
    icon: quote
    columns:

      - width: 2/3
        sections:
          infosTexts:
            type: fields
            fields:
              presentation:
                type: markdown
                label: Présentation
              mentions:
                type: markdown
                label: Mentions légales

      - width: 1/3
        sections:
          infosContact:
            type: fields
            fields:
              contactField:
                type: markdown
                label: Contact
              descriptionSeo:
                type: markdown
                label: Description Page d'accueil (pour référencement)

          logotype:
            type: files
            headline: Logotype BL
            layout: cards
            template: logotype
            max: 1
            image: 
              back: white

          imageSeo:
            type: files
            headline: Image Page d'accueil (pour référencement)
            layout: cards
            template: imageseo
            max: 1
            image: 
              back: white


#-- 3. PAGE D'ACCUIEL

  homepage:
    label: Page d'accueil
    icon: dashboard
    columns:

      - width: 1/1
        sections:
          homepageFeed:
            type: fields
            fields:
              feeds:
                type: quickpages
                query: site.children.template('projet').filterBy('feedhome', '*=', 'true')
                text: '{{ page.legendeAuto.toCaption("home") }}'
                layout: cards
                default: 
                  - lalloz
                size: small
                image:
                  back: white
                  query: page.toFeedImage
                label: Homepage

  
  matomo:
    label: Analytics
    icon: preview
    columns:

      - width: 3/4
        sections:
          main:
            type: matomo-main
      - width: 1/4
        sections:
          sidebar:
            type: matomo-sidebar
            link: false