### PAGE D'ACCUEIL

title: Site

#-----------------------------------------------------------------------------------

# 1. PROJETS
# 2. FEEDS
# 3. INFORMATIONS
	
#-----------------------------------------------------------------------------------

tabs:

#-- 1. PROJETS

  projets:
    label: Projets
    icon: image
    sections:
      projetsListed:
        type: pagetable
        headline: Projets
        template: projet
        status: all
        image:
          cover: true
        columns:
          title:
            label: Titre
            text: '{{ page.title }}'
            width: 1/4
          category:
            label: Catégorie
            text: '{{ page.categorie.toCategory }}'
            width: 1/4
          legende:
            label: Légende
            text: '{{ page.legendeAuto.toCaption }}'
            width: 1/2

      projetsDatas:
        type: fields
        fields:
          line-a:
            type: line

          clients:
            type: tags
            label: Clients
            width: 1/2
          collections: 
            type: tags
            label: Collections
            width: 1/2
    

#-- 2. FEEDS

  feeds:
    label: Feeds
    icon: dashboard
    sections:
      feedsListed:
        sortable: false
        extends: sections/pagelist
        headline: Feeds de projets
        template: feeds
        status: listed
        min: 4
        max: 4
            

#-- 3. INFORMATIONS

  informations:
    label: Informations
    icon: quote
    columns:

      - width: 2/3
        sections:
          infosTexts:
            type: fields
            fields:
              presentation:
                type: markdown
                label: Présentation

      - width: 1/3
        sections:
          infosContact:
            type: fields
            fields:
              email:
                type: email
                label: Adresse email
              instagram:
                label: Compte Instagram
                type: text
                icon: instagram
                before: "@"
          
          contactImage:
            type: files
            headline: Image Benoit Lalloz
            layout: cards
            template: cover
            max: 1
            image: 
              back: white

          logotype:
            type: files
            headline: Logotype BL
            layout: cards
            template: logotype
            max: 1
            image: 
              back: white
            
